[package]
name = "chrome_preferences_replace"
version = "1.1.9"
description = "Replaces exit_type and exited_cleanly inside the Preferences file to avoid the Restore dialog"
authors = ["Luciano Bestia <LucianoBestia@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
unwrap="1.2.1"

